#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdarg.h>
#include <string.h>
#include "set.h"

/* generated by bison */
int yyparse();



int main() {
    printf("Set Calculator Started.\n");
    printf("Enter commands (e.g., let A = {1, 2})\n");
    printf("> ");

    /* Turning on the parser */
    int result = yyparse();

    return result;
}